name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: aliyun4533222819
        password: Wyh1234@
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/flik007/nastools-fixed:2.9.1 docker://registry.cn-hangzhou.aliyuncs.com/nastoolwu/nas-tools:2.9.1
      #skopeo copy docker://docker.io/hslr/sun-panel:1.4.0 docker://registry.cn-guangzhou.aliyuncs.com/nastoolwu/sun-panel:1.4.0
#yohe/nastool:2.9https://registry.hub.docker.com/r/yohe/nastool/tags ghcr.io/monlor/xiaoya-alist ghcr.io/monlor/xiaoya-metadataregistry.hub.docker.com/r/flik007/nastools-fixed 

